#!/bin/bash


DEBUG=0 # Debug Value such that beam is not removed from the git folder, current not in use
VERSION=1.1.0
if [[ $DEBUG == 1 ]]; then
	echo "Running in DEBUG mode"
fi

if [[ ! -d "$HOME/.beam" ]]; then
	mkdir $HOME/.beam
	echo "[!] No $HOME/.beam directory found. Creating it"
fi

if [[ $1 == '' ]]; then
       echo -e "Usage: beam <name> - Connect via OpenVPN\n       beam install - Install the script such that you can use it anywhere\n       beam uninstall - Remove script and all of the OpenVPN files\n       beam push <path_to_openvpn_file> <name> - Add a connection file to beam\n       beam remove <name> - Remove a connection file from beam\n        beam version - Shows the version and credits of beam\n       beam list - List all possible connections beam can make\nDescription: Beam is a OpenVPN manager written in bash."
	exit 0
fi

if [[ $1 == "install" ]]; then
	if [[ $0 == "$HOME/.local/bin/beam" ]]; then
		echo "The script is already installed"
		exit 1
	fi
	if [[ ! -d "$HOME/.local/bin/" ]]; then
		mkdir -p $HOME/.local/bin/
	fi
	cp $0 $HOME/.local/bin/beam
	echo "Finished installing beam"
	exit 0
fi

if [[ $1 == "uninstall" ]]; then
	echo "Are you sure? [Y|n - Default n] (ALL files will be deleted including the ovpn files in ~/.beam:"
	read input
	if [[ $input == 'Y' ]]; then
		echo "Deleting beam"
		rm $HOME/.beam/*
		rmdir $HOME/.beam
		rm $0
	fi
	exit 0
fi

if [[ $1 == "push" ]]; then
	if [[ ! -f $2 ]]; then
		echo "File not found. Please provide a valid file path."
		exit 1
	fi
	cp $2 $HOME/.beam/$3.ovpn
	echo "Successfully added $2 as $3 to beam."
	exit 0
fi

if [[ $1 == "list" ]]; then
	echo "Possible VPN connections:"
	echo ""
	for file in $HOME/.beam/*.ovpn
	do
		
		first=${file//.ovpn}
		substring=$HOME/.beam/
		second=${first/#$substring/''}
		echo "- "$second
	done
	exit 0
fi

if [[ $1 == "remove" ]]; then	
	if [[ ! -f $HOME/.beam/$2.ovpn ]]; then
		echo "Name not found please provide a valid name. See 'beam list'"
		exit 1
	fi
	echo "Are you sure you want to remove $2 from beam? [Y|n - Default n ]"
	read input
	if [[ $input == 'Y' ]]; then
		rm $HOME/.beam/$2.ovpn
		echo "Successfully removed $2 from beam."
	fi
	exit 0
fi

if [[ $1 == "version" ]]; then
	echo -e "
			  	##
			  	##	##
			##     	##	##
			##     	##	##
			##	##	##
		 ██████╗ ███████╗ █████╗ ███╗   ███╗
	    	 ██╔══██╗██╔════╝██╔══██╗████╗ ████║
	   ####	 ██████╔╝█████╗  ███████║██╔████╔██║  ####
	 ######	 ██╔══██╗██╔══╝  ██╔══██║██║╚██╔╝██║  ######
        ####	 ██████╔╝███████╗██║  ██║██║ ╚═╝ ██║     ####
 	 ####    ╚═════╝ ╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝    ####
	   ####		##	##	##	      ####
	     ########                           ########
	      	   ###############################"

	echo "Version: $VERSION"
	echo "Credits: Sol - Twitter: @hydr0nium_"
	exit 0
fi

if [[ ! -f "$HOME/.beam/$1.ovpn" ]]; then
	echo "File not found. Check if $1.ovpn is in $HOME/.beam/"
	exit 1
fi
sudo -k openvpn $HOME/.beam/$1.ovpn

